stages:
  - build
  - release


build:
  image: microsoft/dotnet:latest
  stage: build
  only:
    - master
  script:
    - dotnet restore
    - cd VKBot
    - dotnet publish -c Release -o ./bin/Release
    - cp ../Dockerfile ./bin/Release/netcoreapp2.0
  artifacts:
    paths:
      - VKBot/bin/Release/netcoreapp2.0
    expire_in: 2 days

release:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind

  stage: release
  only:
    - master
  dependencies:
    - build
  script:
    - cd VKBot/bin/Release/netcoreapp2.0
    - echo $CI_BOT_LOGIN > login.json
    - echo {} > config.json
    - docker login -u Renerick -p $GITLAB_ACCESS_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/renerick/vkbot .
    - docker push registry.gitlab.com/renerick/vkbot



