stages:
  - build
  - release
  - deploy

variables:
  DOTNET_PUBLISH_PATH: ./bin/Release/publish

build:
  image: microsoft/dotnet:latest
  stage: build
  only:
    - master
  script:
    - dotnet restore
    - cd VKBot
    - dotnet publish -c Release -o $DOTNET_PUBLISH_PATH
    - cp ../Dockerfile $DOTNET_PUBLISH_PATH
  artifacts:
    paths:
      - VKBot/$DOTNET_PUBLISH_PATH
    expire_in: 2 days

release:
  stage: release
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind

  only:
    - master
  dependencies:
    - build
  script:
    - cd VKBot/$DOTNET_PUBLISH_PATH
    - echo $CI_BOT_LOGIN > login.json
    - echo {} > config.json
    - docker login -u Renerick -p $GITLAB_ACCESS_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/renerick/vkbot .
    - docker push registry.gitlab.com/renerick/vkbot

deploy:
  stage: deploy
  image: kroniak/ssh-client
  when: manual

  environment:
    name: deploy

  only:
    - master
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - scp ./docker-compose.yml $DEPLOY_SERVER:~/docker
    - ssh $DEPLOY_SERVER 'bash -s' < ./docker/deploy.sh




