image: microsoft/dotnet:latest
stages:
  - build

before_script:
  - dotnet restore

build:
  only:
    - master
  stage: build
  script:
    - cd VKBot
    - echo $CI_BOT_LOGIN > login.json
    - echo {} > config.json
    - dotnet run

