stages:
  - build
  - release

before_script:
  - dotnet restore

build:
  image: microsoft/dotnet:latest
  stage: build
  only:
    - master
  script:
    - cd VKBot
    - dotnet publish -c Release -o ./bin/Release
    - cp ../Dockerfile ./bin/Release/netcoreapp2.0
  artifacts:
    paths:
      - ./bin/Release/netcoreapp2.0/
    expire_in: 2 days

release:
  image: docker:latest
  stage: release
  only:
    - master
  dependencies:
    - build
  script:
    - sudo docker login -u Renerick -p $GITLAB_ACCESS_TOKEN registry.gitlab.com
    - sudo docker build -t registry.gitlab.com/renerick/vkbot .
    - sudo docker push registry.gitlab.com/renerick/vkbot



